# Generated by Django 6.1 on 2026-09-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_tag_note_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='cor',
        ),
    ]
